-- Sentencias DML

-- insert, update, delete, select

CREATE SCHEMA EJEMPLO3;

CREATE TABLE EJEMPLO3.ANIMAL(
ID_ANIMAL INT NOT NULL AUTO_INCREMENT,
NOMBRE_ANIMAL VARCHAR(40),
EDAD INT,
FECHA_NACIMIENTO DATE,
TIPO_ANIMAL ENUM ('PERRO', 'GATO'),
PRIMARY KEY(ID_ANIMAL)
);

CREATE TABLE EJEMPLO3.ANIMAL2(
ID_ANIMAL INT NOT NULL AUTO_INCREMENT,
NOMBRE_ANIMAL VARCHAR(40),
EDAD INT,
FECHA_NACIMIENTO DATE,
TIPO_ANIMAL ENUM ('PERRO', 'GATO'),
PRIMARY KEY(ID_ANIMAL)
);


-- CUANDO QUIERO LLENAR TODOS LOS CAMPOS

INSERT INTO EJEMPLO3.ANIMAL VALUES (2, 'PLILI2', 20, '2011-11-11', 'GATO');

-- CUANDO QUIERO INSERTAR DATOS ESPECIFICOS

INSERT INTO EJEMPLO3.ANIMAL (ID_ANIMAL,NOMBRE_ANIMAL, TIPO_ANIMAL) VALUES (1,'PILI','PERRO');
INSERT INTO EJEMPLO3.ANIMAL (NOMBRE_ANIMAL, TIPO_ANIMAL) VALUES ('PILI','PERRO');

-- ALTER PARA METER UN CAMPO LONBLOG PARA UNA IMAGEN

ALTER TABLE EJEMPLO3.ANIMAL ADD COLUMN FOTO longblob;

INSERT INTO EJEMPLO3.ANIMAL (NOMBRE_ANIMAL, TIPO_ANIMAL, FOTO) 
VALUES ('PILI','PERRO', load_file('C:/imagen/maxresdefault.jpg'));

INSERT INTO EJEMPLO3.ANIMAL2  (ID_ANIMAL, NOMBRE_ANIMAL, EDAD, FECHA_NACIMIENTO, TIPO_ANIMAL)
SELECT A.ID_ANIMAL, A.NOMBRE_ANIMAL, A.EDAD, A.FECHA_NACIMIENTO, A.TIPO_ANIMAL FROM EJEMPLO3.ANIMAL A WHERE A.ID_ANIMAL=34;

ALTER TABLE EJEMPLO3.ANIMAL2 ADD COLUMN FOTO longblob;

INSERT INTO EJEMPLO3.ANIMAL2  
SELECT * FROM EJEMPLO3.ANIMAL A WHERE A.ID_ANIMAL=34;

-- cuando necesito insertar varios registros en una sola sentencia insert
INSERT INTO EJEMPLO3.ANIMAL (NOMBRE_ANIMAL, TIPO_ANIMAL, FOTO) 
VALUES ('PILI','PERRO', load_file('C:/imagen/maxresdefault.jpg')),
('PILI','PERRO', load_file('C:/imagen/maxresdefault.jpg')),
('PILI','PERRO', load_file('C:/imagen/maxresdefault.jpg')),
('PILI','PERRO', load_file('C:/imagen/maxresdefault.jpg')),
('PILI','PERRO', load_file('C:/imagen/maxresdefault.jpg'));


-- replace

REPLACE INTO EJEMPLO3.ANIMAL (ID_ANIMAL,NOMBRE_ANIMAL, TIPO_ANIMAL, FOTO)
VALUES (50,'PILI','PERRO', load_file('C:/imagen/maxresdefault.jpg'));

-- UPDATE ACTUALIZAR

UPDATE EJEMPLO3.ANIMAL SET NOMBRE_ANIMAL= 'JAJAJAJA', TIPO_ANIMAL= 'GATO'  WHERE ID_ANIMAL =1;

UPDATE EJEMPLO3.ANIMAL SET  TIPO_ANIMAL= 'GATO'  WHERE ID_ANIMAL<10 AND ID_ANIMAL>5 LIMIT 2;

UPDATE EJEMPLO3.ANIMAL SET  TIPO_ANIMAL= 'GATO'  WHERE ID_ANIMAL<51  ORDER BY ID_ANIMAL ASC LIMIT 5;

-- DELETE BORRAR 

DELETE FROM EJEMPLO3.ANIMAL WHERE ID_ANIMAL=1;

DELETE FROM EJEMPLO3.ANIMAL WHERE ID_ANIMAL>=5 AND ID_ANIMAL<=10;

DELETE FROM EJEMPLO3.ANIMAL WHERE ID_ANIMAL>=1 ORDER BY ID_ANIMAL DESC LIMIT 5;

-- SELECT CONSULTAR

SELECT * FROM EJEMPLO3.ANIMAL;
SELECT NOMBRE_ANIMAL, TIPO_ANIMAL FROM EJEMPLO3.ANIMAL;
SELECT NOMBRE_ANIMAL, TIPO_ANIMAL FROM EJEMPLO3.ANIMAL WHERE ID_ANIMAL = 11;









